/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedDashboardChar123PostIdChar125RouteImport } from './routes/_authed/dashboard/{-$postId}'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardChar123PostIdChar125Route =
  AuthedDashboardChar123PostIdChar125RouteImport.update({
    id: '/dashboard/{-$postId}',
    path: '/dashboard/{-$postId}',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/{-$postId}': typeof AuthedDashboardChar123PostIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/{-$postId}': typeof AuthedDashboardChar123PostIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/dashboard/{-$postId}': typeof AuthedDashboardChar123PostIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/{-$postId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/{-$postId}'
  id: '__root__' | '/' | '/_authed' | '/_authed/dashboard/{-$postId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/{-$postId}': {
      id: '/_authed/dashboard/{-$postId}'
      path: '/dashboard/{-$postId}'
      fullPath: '/dashboard/{-$postId}'
      preLoaderRoute: typeof AuthedDashboardChar123PostIdChar125RouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardChar123PostIdChar125Route: typeof AuthedDashboardChar123PostIdChar125Route
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardChar123PostIdChar125Route:
    AuthedDashboardChar123PostIdChar125Route,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
