/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthedDashboardChar123PostIdChar125RouteImport } from './routes/_authed/dashboard/{-$postId}'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthedDashboardChar123PostIdChar125Route =
  AuthedDashboardChar123PostIdChar125RouteImport.update({
    id: '/dashboard/{-$postId}',
    path: '/dashboard/{-$postId}',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dashboard/{-$postId}': typeof AuthedDashboardChar123PostIdChar125Route
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/dashboard/{-$postId}': typeof AuthedDashboardChar123PostIdChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_authed': typeof AuthedRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_authed/dashboard/{-$postId}': typeof AuthedDashboardChar123PostIdChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/{-$postId}'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/{-$postId}'
  id:
    | '__root__'
    | '/_app'
    | '/_authed'
    | '/_app/'
    | '/_authed/dashboard/{-$postId}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_authed/dashboard/{-$postId}': {
      id: '/_authed/dashboard/{-$postId}'
      path: '/dashboard/{-$postId}'
      fullPath: '/dashboard/{-$postId}'
      preLoaderRoute: typeof AuthedDashboardChar123PostIdChar125RouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthedRouteChildren {
  AuthedDashboardChar123PostIdChar125Route: typeof AuthedDashboardChar123PostIdChar125Route
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardChar123PostIdChar125Route:
    AuthedDashboardChar123PostIdChar125Route,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
